apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    route:
      enabled: true
    ingress:
      enabled: false
    insecure: false
    resources: {}
  dex:
    image: quay.io/ablock/dex
    openShiftOAuth: true
    version: openshift-connector
  helpChatURL: https://chat.google.com/room/AAAAonnPp64
  helpChatText: "Red Hat Workshop Chat"
  rbac:
    defaultPolicy: role:admin