apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- argocd.yaml
#- networkpolicy-router.yaml
#- networkpolicy-pipeline.yaml

bases: 
- ../operator_and_subscription