apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rh-helloworld
  labels:
    app: rh-helloworld
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0.1-12
    from:
      kind: DockerImage
      name: quay.io/hluong/helloworld-python:0.0.1-12
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: 0.0.1-13
    from:
      kind: DockerImage
      name: quay.io/hluong/helloworld-python:0.0.1-13
    importPolicy: {}
    referencePolicy:
      type: Local
