apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argocd-namespace.yaml
- argocd-operatorgroup.yaml
- argocd-subscription.yaml
- argocd-application-controller-cluster-adminrole-binding.yaml