apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rh-helloworld-dev-env
bases:
- ../../bases/rh-helloworld
# check whether or not we need team-rolebinding
resources:
- rh-helloworld-namespace.yaml
images:
- name: rh-helloworld
  newName: image-registry.openshift-image-registry.svc:5000/rh-helloworld-dev-env/rh-helloworld
  newTag: 0.0.1-2
